# Generated by Django 2.1.3 on 2019-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190115_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Заголовок'),
        ),
    ]
