# Generated by Django 2.1.3 on 2018-12-11 18:09

import applications.banners.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рекламной кaмпании или акции', max_length=150, verbose_name='Кампания (Название)')),
                ('image', models.ImageField(help_text='Размер изображения должен быть 1170x382', upload_to=applications.banners.models.get_file_path, validators=[applications.banners.models.image_validator], verbose_name='Изображение')),
                ('url', models.URLField(blank=True, help_text='URL на который произойдет перенаправление при клике на баннер.', verbose_name='URL перенаправления')),
                ('start_date', models.DateField(default=None, help_text='Дата когда начать показ баннера.', verbose_name='Дата запуска')),
                ('end_date', models.DateField(default=None, help_text='Дата когда завершить показ баннера.', verbose_name='Дата завершения')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BannerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_view', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество показов')),
                ('count_click', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество переходов')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удален')),
                ('banner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='banners.Banner', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Статистика по баннерам',
                'verbose_name_plural': 'Статистика по баннерам',
            },
        ),
    ]
