# Generated by Django 2.1.3 on 2018-12-15 15:58

import applications.banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Размер изображения должен быть 1440x320', upload_to=applications.banners.models.get_file_path, validators=[applications.banners.models.image_validator], verbose_name='Изображение'),
        ),
    ]
