version: '3'
services:

  nginx:
    image: nginx:1.15
    restart: always
    env_file:
      - .denv
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/robots.txt:/etc/nginx/robots.txt
      - /root/letsencrypt/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - medias:/media
      - statics:/static
      - common:/common_files
    ports:
      - 80:80
      - 443:443

  core:
    build: .
    image: registry.gitlab.com/stanislav.dev3/neotelecom
    restart: always
    command: uwsgi --ini /core/uwsgi.conf
    env_file:
      - .denv
    networks:
      - local
    volumes:
      - ./etc/uwsgi.conf:/core/uwsgi.conf
      - statics:/core/static
      - medias:/core/media
      - common:/common_files
    depends_on:
      - postgres-db
      - nginx

  tbot:
    image: registry.gitlab.com/stanislav.dev3/neotelecom
    restart: always
    command: python manage.py start_bot
    env_file:
      - .denv
    networks:
      - local
    depends_on:
      - postgres-db
      - nginx

  postgres-db:
    image: postgres:11.1
    restart: always
    env_file:
      - .denv
    networks:
      - local
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

networks:
  local:

volumes:
  common:
  pgdata:
  statics:
  medias:
