# Generated by Django 2.1.3 on 2018-12-11 18:09

import applications.promotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=150, verbose_name='Подзаголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=applications.promotions.models.get_file_path, verbose_name='Изображение')),
                ('bullet_one', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='1-й буллет')),
                ('bullet_two', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='2-й буллет')),
                ('bullet_three', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='3-й буллет')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('price_type', models.IntegerField(choices=[(0, 'сом/сутки'), (1, 'сом/неделю'), (2, 'сом/месяц')], default=0, verbose_name='Тип цены')),
                ('start_date', models.DateField(help_text='Дата когда начать показ акции.', verbose_name='Дата запуска')),
                ('end_date', models.DateField(help_text='Дата когда завершить показ акции.', verbose_name='Дата завершения')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удалена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
