# Generated by Django 2.1.3 on 2018-12-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['created_at'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
