# Generated by Django 2.1.3 on 2018-12-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_joinus_form_type'),
        ('promotions', '0002_auto_20181216_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='city',
            field=models.ManyToManyField(help_text='Список городов на которые распространяется акция', to='core.City', verbose_name='Города'),
        ),
    ]
