# Generated by Django 2.1.3 on 2019-01-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20181226_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
