# Generated by Django 2.1.3 on 2019-01-17 09:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_auto_20190115_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500, verbose_name='Описание'),
        ),
    ]
