# Generated by Django 2.1.3 on 2018-12-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handbook',
            options={'ordering': ['position'], 'verbose_name': 'справочник', 'verbose_name_plural': 'справочник'},
        ),
        migrations.AddField(
            model_name='handbook',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Позиция в спике'),
        ),
    ]
