# Generated by Django 2.1.3 on 2019-01-17 09:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_auto_20181224_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Информация'),
        ),
    ]
