# Generated by Django 2.1.3 on 2018-12-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='Скорость ДО Мбит/сек')),
                ('price', models.PositiveIntegerField(verbose_name='Абонентская плата в месяц')),
                ('extra_neo_tv', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество точек NeoTv')),
                ('extra_smart_tv', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество точек SmartTv')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Интернет тариф',
                'verbose_name_plural': 'Интернет тарифы',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SmartTvTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('channels_count', models.PositiveSmallIntegerField(verbose_name='Количество телеканалов')),
                ('price', models.PositiveIntegerField(verbose_name='Абонентская плата в сутки')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('city', models.ManyToManyField(help_text='Список городов на которые распространяется данный тариф', to='core.City', verbose_name='Города')),
            ],
            options={
                'verbose_name': 'Тариф SmartTv',
                'verbose_name_plural': 'Тарифы SmartTv',
                'ordering': ['position'],
            },
        ),
    ]
