# Generated by Django 2.1.3 on 2018-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internettariff',
            name='tech_type',
            field=models.CharField(blank=True, choices=[('gpon', 'GPON'), ('4g', '4G')], max_length=50, null=True, verbose_name='Технология'),
        ),
    ]
