# Generated by Django 2.1.3 on 2018-12-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181215_2205'),
        ('tariffs', '0003_internettariff_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('channels_count', models.PositiveSmallIntegerField(verbose_name='Количество телеканалов')),
                ('price', models.PositiveIntegerField(verbose_name='Абонентская плата')),
                ('price_type', models.IntegerField(choices=[(0, 'сом/сут.'), (1, 'сом/нед.'), (2, 'сом/мес.')], default=2, verbose_name='Тип цены')),
                ('extra_package', models.BooleanField(default=False, verbose_name='Дополнительный пакет')),
                ('tech_type', models.CharField(blank=True, choices=[('smart_tv', 'Smart TV'), ('neo_tv', 'NEO TV')], max_length=50, null=True, verbose_name='Технология')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('city', models.ManyToManyField(help_text='Список городов на которые распространяется данный тариф', to='core.City', verbose_name='Города')),
            ],
            options={
                'verbose_name': 'Тариф TV',
                'verbose_name_plural': 'Тарифы TV',
                'ordering': ['position'],
            },
        ),
        migrations.RemoveField(
            model_name='smarttvtariff',
            name='city',
        ),
        migrations.AlterField(
            model_name='internettariff',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Абонентская плата'),
        ),
        migrations.DeleteModel(
            name='SmartTvTariff',
        ),
    ]
