# Generated by Django 2.1.3 on 2018-12-11 18:09
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def create_default_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create(
        username='cheetah',
        email='stanislav.dev3@gmail.com',
        password=make_password('admin!@#$%^&'),
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )


def create_default_cities(apps, schema_editor):
    City = apps.get_model('core', 'City')
    City.objects.get_or_create(
        title='Бишкек',
        slug='bishkek',
        is_active=True
    )
    City.objects.get_or_create(
        title='Ош',
        slug='osh',
        is_active=True
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Город')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг города')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('ownership', models.CharField(choices=[('fiz', 'Физическе лицо'), ('yur', 'Юридическое лицо')], default='', max_length=50, verbose_name='Форма собственности')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('acepted', 'Принятая заявка')], default='new', max_length=50, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(create_default_superuser),
        migrations.RunPython(create_default_cities),
    ]
