# Generated by Django 2.1.3 on 2019-01-15 06:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181223_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('short_description', models.CharField(help_text='Краткий текст в списке вакансий для вовлечения соискателей.', max_length=250, verbose_name='Краткое описание')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'вакансию',
                'verbose_name_plural': 'вакансии',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='callme',
            options={'ordering': ['created_at'], 'verbose_name': 'звонок', 'verbose_name_plural': 'звонки'},
        ),
        migrations.AlterModelOptions(
            name='joinus',
            options={'ordering': ['created_at'], 'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
    ]
