# Generated by Django 2.1.3 on 2019-01-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190115_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callme',
            options={'ordering': ['-created_at'], 'verbose_name': 'звонок', 'verbose_name_plural': 'звонки'},
        ),
        migrations.AlterModelOptions(
            name='joinus',
            options={'ordering': ['-created_at'], 'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'вакансию', 'verbose_name_plural': 'вакансии'},
        ),
    ]
