# Generated by Django 2.1.3 on 2019-01-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190115_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeoTvFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('win', 'Windows'), ('macos', 'Mac OS'), ('armv7', 'Android arm v7'), ('armx64', 'Android arm x64'), ('armx86', 'Android arm x86')], max_length=50, unique=True, verbose_name='Тип файла')),
                ('url', models.FileField(upload_to='neo_tv_files/', verbose_name='Файл для загрузки')),
            ],
            options={
                'verbose_name': 'приложение NEO TV',
                'verbose_name_plural': 'приложения NEO TV',
            },
        ),
    ]
