# Generated by Django 2.1.3 on 2019-01-17 09:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_neotvfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
