# Generated by Django 2.1.3 on 2019-10-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190117_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neotvfiles',
            name='type',
            field=models.CharField(choices=[('win', 'Windows'), ('macos', 'Mac OS'), ('armv7', 'Android arm v7'), ('armx64', 'Android arm x64'), ('armx86', 'Android arm x86'), ('youtube', 'YouTube плеер')], max_length=50, unique=True, verbose_name='Тип файла'),
        ),
    ]
